export default [
    {
      id: 1,
      img: 'https://images-na.ssl-images-amazon.com/images/I/51qBHRNusSL._AC_SY350_.jpg',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      price: 10,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat imperdiet leo, vitae congue est efficitur eget. Nunc tempor urna ac malesuada varius. Sed feugiat porta erat sit amet imperdiet. In pellentesque urna vitae ullamcorper finibus. Integer ac efficitur sem. Aenean feugiat eu ligula a convallis. Nulla varius dictum nibh sodales fringilla.',
      full_description: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique, sans que son contenu n\'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.',
      author: 'author',
    },
    {
      id: 2,
      img: 'https://images-na.ssl-images-amazon.com/images/I/51qBHRNusSL._AC_SY350_.jpg',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      price: 20,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat imperdiet leo, vitae congue est efficitur eget. Nunc tempor urna ac malesuada varius. Sed feugiat porta erat sit amet imperdiet. In pellentesque urna vitae ullamcorper finibus. Integer ac efficitur sem. Aenean feugiat eu ligula a convallis. Nulla varius dictum nibh sodales fringilla.',
      full_description: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique, sans que son contenu n\'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.',
      author: 'author',
    },
    {
      id: 3,
      img: 'https://images-na.ssl-images-amazon.com/images/I/51qBHRNusSL._AC_SY350_.jpg',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      price: 30,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat imperdiet leo, vitae congue est efficitur eget. Nunc tempor urna ac malesuada varius. Sed feugiat porta erat sit amet imperdiet. In pellentesque urna vitae ullamcorper finibus. Integer ac efficitur sem. Aenean feugiat eu ligula a convallis. Nulla varius dictum nibh sodales fringilla.',
      full_description: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique, sans que son contenu n\'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.',
      author: 'author',
    },
    {
      id: 4,
      img: 'https://images-na.ssl-images-amazon.com/images/I/51qBHRNusSL._AC_SY350_.jpg',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      price: 40,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat imperdiet leo, vitae congue est efficitur eget. Nunc tempor urna ac malesuada varius. Sed feugiat porta erat sit amet imperdiet. In pellentesque urna vitae ullamcorper finibus. Integer ac efficitur sem. Aenean feugiat eu ligula a convallis. Nulla varius dictum nibh sodales fringilla.',
      full_description: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique, sans que son contenu n\'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.',
      author: 'author',
    },
    {
      id: 5,
      img: 'https://images-na.ssl-images-amazon.com/images/I/51qBHRNusSL._AC_SY350_.jpg',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      price: 50,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat imperdiet leo, vitae congue est efficitur eget. Nunc tempor urna ac malesuada varius. Sed feugiat porta erat sit amet imperdiet. In pellentesque urna vitae ullamcorper finibus. Integer ac efficitur sem. Aenean feugiat eu ligula a convallis. Nulla varius dictum nibh sodales fringilla.',
      full_description: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique, sans que son contenu n\'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.',
      author: 'author',
    },
    {
      id: 6,
      img: 'https://images-na.ssl-images-amazon.com/images/I/51qBHRNusSL._AC_SY350_.jpg',
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      price: 60,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat imperdiet leo, vitae congue est efficitur eget. Nunc tempor urna ac malesuada varius. Sed feugiat porta erat sit amet imperdiet. In pellentesque urna vitae ullamcorper finibus. Integer ac efficitur sem. Aenean feugiat eu ligula a convallis. Nulla varius dictum nibh sodales fringilla.',
      full_description: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, mais s\'est aussi adapté à la bureautique informatique, sans que son contenu n\'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.',
      author: 'author',
    },
  ];